### ISSUE TITLE
ecto.migrate crashing

### ISSUE THREAD

**Issue by trbngr** [elixir-ecto/ecto_sql#64] opened 2018-12-24 19:45 UTC
### Environment

* Elixir version (elixir -v):Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): (PostgreSQL) 11.1
* Ecto version (mix deps): ecto 3.0.5 (Hex package) (mix)
* Database adapter and version (mix deps): ecto_sql 3.0.3
* Operating system: macOS 10.14.2 (18C54)

### Current behavior

Running `ecto.migrate` runs all migrations and finishes...with a crash.

I have a alias setup to run migrations for a few repos. But mix crashes after the first repo is migrated.

ie. `mix ecto.migrate --repo A --repo B` will migrate repo `A` but exit before migrating `B`.

It seems that the offender is [this](https://github.com/elixir-ecto/ecto_sql/blob/master/lib/mix/tasks/ecto.migrate.ex#L114). I can comment that out and it works as expected.

### Expected behavior

My team and I would like to be able to migrate all repos without extra typing. :)

**Comment by josevalim** [comment] 2018-12-24 20:18
Can you please include the crash in your report? Thank you.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment] 2018-12-25 10:43
Unfortunately I cannot reproduce this. Can you please provide a minimal app that reproduces the error? Thanks!

**Comment by josevalim** [comment] 2019-01-31 22:46
Closing  this. Please let us  know if you have more info.

**Closed by josevalim** 2019-01-31 22:46 UTC
Labels: Note:Needs more info
